version: "3"
services:
  db:
    image: mongo:3
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: n00pP@$$
    container_name: "db"
    ports:
      - 27017:27017
  lazy-server:
    environment:
      - DB_SERVER=db
      - LAZY_DB=cpt4lazyDB
#      - DB_USER=root
#      - DB_PORT=27017
#      - DB_PASSWORD=n00pP@$$
    build: .
    container_name: cpt4lazyserver
    ports:
      - 8080:8080
    links:
      - db
