version: "3"
services:
  db:
    image: mongo:3
    restart: always
    container_name: "db"
    ports:
      - 27017:27017
  lazy-server:
    environment:
      - DB_SERVER=db
      - LAZY_DB=cpt4lazyDB
    build: .
    container_name: cpt4lazyserver
    ports:q
      - 8080:8080
    links:
      - db
